windows:
  hosts:
    dc01:
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_user: .\USERNAME
      ansible_password: PASSWORD
      ansible_winrm_transport: ntlm