#misc-security.yaml
---
- name: Security Management Tasks
  hosts: windows
  tasks:
    - name: Install all security updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        state: installed
      # Dieser Task stellt sicher, dass alle Sicherheitsupdates installiert sind.

    - name: Ensure firewall rule exists
      community.windows.win_firewall_rule:
        name: "Allow HTTP"
        localport: 80
        action: allow
        direction: In
        protocol: Tcp
      # Dieser Task stellt sicher, dass eine Firewall-Regel für eingehenden HTTP-Verkehr (Port 80) existiert und erlaubt ist.

    - name: Configure Audit Policy
      community.windows.win_audit_policy_system:
        subcategory: "Logon"
        success: enable
        failure: enable
      # Dieser Task konfiguriert die Audit-Richtlinie, um sowohl erfolgreiche als auch fehlgeschlagene Anmeldevorgänge zu protokollieren.

    - name: Ensure SMB v1 is disabled
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: SMB1
        data: 0
        type: dword
      # Dieser Task stellt sicher, dass SMB v1 im Windows-System deaktiviert ist.
      
    - name: Enable system events
      community.windows.win_security_policy:
        section: Event Audit
        key: AuditSystemEvents
        value: 1
      # Dieser Task aktiviert die Protokollierung von Systemereignissen.
