#password-config.yaml
---
- name: Password Management Tasks
  hosts: windows
  tasks:
    - name: Set the maximum password age
      community.windows.win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: 30
      # Dieser Task setzt das maximale Passwortalter auf 30 Tage.

    - name: Do not store passwords using reversible encryption
      community.windows.win_security_policy:
        section: System Access
        key: ClearTextPassword
        value: 0
      # Dieser Task stellt sicher, dass Passwörter nicht mit reversibler Verschlüsselung gespeichert werden.

    - name: Ensure 'Enforce password history' is set to '24 or more password(s)'
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: PasswordHistoryLength
        data: 24
        type: dword
      # Dieser Task stellt sicher, dass die Passworthistorie auf mindestens 24 Passwörter festgelegt ist.