---
- name: Setup default Software
  hosts: win
  tasks:
    - name: Install 7-Zip with Chocolatey
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install Java with Chocolatey
      win_chocolatey:
        name: jdk8
        state: present